In [1]:
#Importing libraries

import pandas as pd
import seaborn as sns
import numpy as np
import regex as re

import matplotlib
import matplotlib.pyplot as plt

%matplotlib inline

In [2]:
#Plot configuration

plt.style.use('ggplot')
from matplotlib.pyplot import figure
plt.rcParams ['figure.figsize'] = (6,8)

In [3]:
# Read the Data

df= pd.read_csv(r'D:\Projects\Python\Netflix\movies.csv')
pd.set_option('display.max_rows', None)
df.head()

,name,rating,genre,year,released,score,votes,director,writer,star,country,budget,gross,company,runtime
0,The Shining,R,Drama,1980,"June 13, 1980 (United States)",8.4,927000.0,Stanley Kubrick,Stephen King,Jack Nicholson,United Kingdom,19000000.0,46998772.0,Warner Bros.,146.0
1,The Blue Lagoon,R,Adventure,1980,"July 2, 1980 (United States)",5.8,65000.0,Randal Kleiser,Henry De Vere Stacpoole,Brooke Shields,United States,4500000.0,58853106.0,Columbia Pictures,104.0
2,Star Wars: Episode V - The Empire Strikes Back,PG,Action,1980,"June 20, 1980 (United States)",8.7,1200000.0,Irvin Kershner,Leigh Brackett,Mark Hamill,United States,18000000.0,538375067.0,Lucasfilm,124.0
3,Airplane!,PG,Comedy,1980,"July 2, 1980 (United States)",7.7,221000.0,Jim Abrahams,Jim Abrahams,Robert Hays,United States,3500000.0,83453539.0,Paramount Pictures,88.0
4,Caddyshack,R,Comedy,1980,"July 25, 1980 (United States)",7.3,108000.0,Harold Ramis,Brian Doyle-Murray,Chevy Chase,United States,6000000.0,39846344.0,Orion Pictures,98.0

In [4]:
#checking missing values

for col in df.columns:
    miss_value = (df[col].isna().sum()/df['name'].count()) * 100
    print ('{} : {:.2f}%'.format(col,miss_value))

name : 0.00%
rating : 1.00%
genre : 0.00%
year : 0.00%
released : 0.03%
score : 0.04%
votes : 0.04%
director : 0.00%
writer : 0.04%
star : 0.01%
country : 0.04%
budget : 28.31%
gross : 2.46%
company : 0.22%
runtime : 0.05%

In [5]:
# Updating missing values


#For Rating column

df['rating'].drop_duplicates()

0               R
2              PG
60              G
78            NaN
83      Not Rated
96          NC-17
120      Approved
201         TV-PG
476         PG-13
691       Unrated
982             X
2689        TV-MA
7607        TV-14
Name: rating, dtype: object

In [6]:
df['rating'] = df['rating'].fillna('Not Rated')
df['rating'] = df['rating'].replace({'Approved':'Not Rated','Unrated':'Not Rated'})

In [7]:
# For Score Column

print(df['score'].isna().sum())
print(df['votes'].isna().sum())

3
3

In [8]:
df['score'] = df['score'].fillna(0)
df['votes'] = df['votes'].fillna(0)

In [9]:
df['writer'] =df['writer'].fillna('Unknown')
df['star'] =df['star'].fillna('Unknown')
df['country'] =df['country'].fillna('Unknown')

In [10]:
#Checking missing values again for further actions

for col in df.columns:
    miss_value = (df[col].isna().sum()/df['name'].count()) * 100
    print('{} {:.2f}%'.format(col,miss_value))

name 0.00%
rating 0.00%
genre 0.00%
year 0.00%
released 0.03%
score 0.00%
votes 0.00%
director 0.00%
writer 0.00%
star 0.00%
country 0.00%
budget 28.31%
gross 2.46%
company 0.22%
runtime 0.05%

In [11]:
df['budget'] = df['budget'].fillna(0)
df['gross'] = df['gross'].fillna(0)
df['runtime'] = df['runtime'].fillna(0)

In [12]:
df['genre'] = df['genre'].fillna('Unknown')
df['company'] = df['company'].fillna('Unknown')

df['genre'] = df['genre'].astype('category')
df['company'] = df['company'].astype('category')

In [13]:
df['released_year'] = df['released'].str.extract(r'\b(\d{4})\b')
df['released_year'] = df['released_year'].fillna(0000)
df.head(10)

,name,rating,genre,year,released,score,votes,director,writer,star,country,budget,gross,company,runtime,released_year
0,The Shining,R,Drama,1980,"June 13, 1980 (United States)",8.4,927000.0,Stanley Kubrick,Stephen King,Jack Nicholson,United Kingdom,19000000.0,46998772.0,Warner Bros.,146.0,1980
1,The Blue Lagoon,R,Adventure,1980,"July 2, 1980 (United States)",5.8,65000.0,Randal Kleiser,Henry De Vere Stacpoole,Brooke Shields,United States,4500000.0,58853106.0,Columbia Pictures,104.0,1980
2,Star Wars: Episode V - The Empire Strikes Back,PG,Action,1980,"June 20, 1980 (United States)",8.7,1200000.0,Irvin Kershner,Leigh Brackett,Mark Hamill,United States,18000000.0,538375067.0,Lucasfilm,124.0,1980
3,Airplane!,PG,Comedy,1980,"July 2, 1980 (United States)",7.7,221000.0,Jim Abrahams,Jim Abrahams,Robert Hays,United States,3500000.0,83453539.0,Paramount Pictures,88.0,1980
4,Caddyshack,R,Comedy,1980,"July 25, 1980 (United States)",7.3,108000.0,Harold Ramis,Brian Doyle-Murray,Chevy Chase,United States,6000000.0,39846344.0,Orion Pictures,98.0,1980
5,Friday the 13th,R,Horror,1980,"May 9, 1980 (United States)",6.4,123000.0,Sean S. Cunningham,Victor Miller,Betsy Palmer,United States,550000.0,39754601.0,Paramount Pictures,95.0,1980
6,The Blues Brothers,R,Action,1980,"June 20, 1980 (United States)",7.9,188000.0,John Landis,Dan Aykroyd,John Belushi,United States,27000000.0,115229890.0,Universal Pictures,133.0,1980
7,Raging Bull,R,Biography,1980,"December 19, 1980 (United States)",8.2,330000.0,Martin Scorsese,Jake LaMotta,Robert De Niro,United States,18000000.0,23402427.0,Chartoff-Winkler Productions,129.0,1980
8,Superman II,PG,Action,1980,"June 19, 1981 (United States)",6.8,101000.0,Richard Lester,Jerry Siegel,Gene Hackman,United States,54000000.0,108185706.0,Dovemead Films,127.0,1981
9,The Long Riders,R,Biography,1980,"May 16, 1980 (United States)",7.0,10000.0,Walter Hill,Bill Bryden,David Carradine,United States,10000000.0,15795189.0,United Artists,100.0,1980

In [14]:
# check missing values for the last time

for col in df.columns:
    miss_value = (df[col].isna().sum()/df['name'].count()) * 100
    print('{} {:.2f}%'.format(col,miss_value))

name 0.00%
rating 0.00%
genre 0.00%
year 0.00%
released 0.03%
score 0.00%
votes 0.00%
director 0.00%
writer 0.00%
star 0.00%
country 0.00%
budget 0.00%
gross 0.00%
company 0.00%
runtime 0.00%
released_year 0.00%

In [15]:
# Updating missing values has been done.

#Now it's time for checking Data types

In [16]:
df.dtypes

name               object
rating             object
genre            category
year                int64
released           object
score             float64
votes             float64
director           object
writer             object
star               object
country            object
budget            float64
gross             float64
company          category
runtime           float64
released_year      object
dtype: object

In [17]:
df['rating'] = df['rating'].astype('category')
df['votes'] = df['votes'].astype('int64')
df['budget'] = df['budget'].astype('int64')
df['gross'] = df['gross'].astype('int64')
df['runtime'] = df['runtime'].astype('int64')

In [18]:
#Checking for the last time

df.dtypes

name               object
rating           category
genre            category
year                int64
released           object
score             float64
votes               int64
director           object
writer             object
star               object
country            object
budget              int64
gross               int64
company          category
runtime             int64
released_year      object
dtype: object

In [19]:
df.head(10)

,name,rating,genre,year,released,score,votes,director,writer,star,country,budget,gross,company,runtime,released_year
0,The Shining,R,Drama,1980,"June 13, 1980 (United States)",8.4,927000,Stanley Kubrick,Stephen King,Jack Nicholson,United Kingdom,19000000,46998772,Warner Bros.,146,1980
1,The Blue Lagoon,R,Adventure,1980,"July 2, 1980 (United States)",5.8,65000,Randal Kleiser,Henry De Vere Stacpoole,Brooke Shields,United States,4500000,58853106,Columbia Pictures,104,1980
2,Star Wars: Episode V - The Empire Strikes Back,PG,Action,1980,"June 20, 1980 (United States)",8.7,1200000,Irvin Kershner,Leigh Brackett,Mark Hamill,United States,18000000,538375067,Lucasfilm,124,1980
3,Airplane!,PG,Comedy,1980,"July 2, 1980 (United States)",7.7,221000,Jim Abrahams,Jim Abrahams,Robert Hays,United States,3500000,83453539,Paramount Pictures,88,1980
4,Caddyshack,R,Comedy,1980,"July 25, 1980 (United States)",7.3,108000,Harold Ramis,Brian Doyle-Murray,Chevy Chase,United States,6000000,39846344,Orion Pictures,98,1980
5,Friday the 13th,R,Horror,1980,"May 9, 1980 (United States)",6.4,123000,Sean S. Cunningham,Victor Miller,Betsy Palmer,United States,550000,39754601,Paramount Pictures,95,1980
6,The Blues Brothers,R,Action,1980,"June 20, 1980 (United States)",7.9,188000,John Landis,Dan Aykroyd,John Belushi,United States,27000000,115229890,Universal Pictures,133,1980
7,Raging Bull,R,Biography,1980,"December 19, 1980 (United States)",8.2,330000,Martin Scorsese,Jake LaMotta,Robert De Niro,United States,18000000,23402427,Chartoff-Winkler Productions,129,1980
8,Superman II,PG,Action,1980,"June 19, 1981 (United States)",6.8,101000,Richard Lester,Jerry Siegel,Gene Hackman,United States,54000000,108185706,Dovemead Films,127,1981
9,The Long Riders,R,Biography,1980,"May 16, 1980 (United States)",7.0,10000,Walter Hill,Bill Bryden,David Carradine,United States,10000000,15795189,United Artists,100,1980

In [20]:
#Since we created 'released_year' column, we drop 'year' and 'released' columns.

df = df.drop(['year','released'], axis=1)
df.head()

,name,rating,genre,score,votes,director,writer,star,country,budget,gross,company,runtime,released_year
0,The Shining,R,Drama,8.4,927000,Stanley Kubrick,Stephen King,Jack Nicholson,United Kingdom,19000000,46998772,Warner Bros.,146,1980
1,The Blue Lagoon,R,Adventure,5.8,65000,Randal Kleiser,Henry De Vere Stacpoole,Brooke Shields,United States,4500000,58853106,Columbia Pictures,104,1980
2,Star Wars: Episode V - The Empire Strikes Back,PG,Action,8.7,1200000,Irvin Kershner,Leigh Brackett,Mark Hamill,United States,18000000,538375067,Lucasfilm,124,1980
3,Airplane!,PG,Comedy,7.7,221000,Jim Abrahams,Jim Abrahams,Robert Hays,United States,3500000,83453539,Paramount Pictures,88,1980
4,Caddyshack,R,Comedy,7.3,108000,Harold Ramis,Brian Doyle-Murray,Chevy Chase,United States,6000000,39846344,Orion Pictures,98,1980

In [21]:
df = df.rename(columns={'released_year':'year'})
df.head()

,name,rating,genre,score,votes,director,writer,star,country,budget,gross,company,runtime,year
0,The Shining,R,Drama,8.4,927000,Stanley Kubrick,Stephen King,Jack Nicholson,United Kingdom,19000000,46998772,Warner Bros.,146,1980
1,The Blue Lagoon,R,Adventure,5.8,65000,Randal Kleiser,Henry De Vere Stacpoole,Brooke Shields,United States,4500000,58853106,Columbia Pictures,104,1980
2,Star Wars: Episode V - The Empire Strikes Back,PG,Action,8.7,1200000,Irvin Kershner,Leigh Brackett,Mark Hamill,United States,18000000,538375067,Lucasfilm,124,1980
3,Airplane!,PG,Comedy,7.7,221000,Jim Abrahams,Jim Abrahams,Robert Hays,United States,3500000,83453539,Paramount Pictures,88,1980
4,Caddyshack,R,Comedy,7.3,108000,Harold Ramis,Brian Doyle-Murray,Chevy Chase,United States,6000000,39846344,Orion Pictures,98,1980